### PR TITLE
fix: key-value data is stored per user instead of per flow

### PR DESCRIPTION
**Pull request by ShaksterNano**
This might break your database

### CODE REVIEW

**Review by insertish — APPROVED** [review]
how does this break my database

**Review by insertish — APPROVED** [review]
approved

**Comment by ShaksterNano** [comment]
> how does this break my database

if you had flow key value data before thats now invalid and will fail to load

**Comment by insertish** [comment]
:trollface:

**Comment by sneexy-boi** [comment]
:trollface:

**Comment by stationaryStation** [comment]
image

**Comment by o69mar** [comment]
:trollface:

**Comment by enygmate** [comment]
image

**Comment by tame1d** [comment]
:trollface:

**Comment by NoLogicAlan** [comment]
:trollface:

**Pull request merged**
