### PR TITLE
feat: create discord gatos plugin

### PR DESCRIPTION
**Pull request by williambl**

### CODE REVIEW

**Comment by williambl** [comment]
:trollface:

**Review by ShaksterNano — APPROVED** [review]

**Comment by williambl** [comment]
no merge silvousplait

**Comment by williambl** [comment]
Todo:
 - [ ] create/modify embed nodes
 - [ ] string -> (emoji/channel/role/user) id nodes
 - [ ] ensure that user has correct perms to create the flows

**Comment by williambl** [comment]
marking as ready for review now. probably shouldn't be merged until we have at least some tests though.

**Review by serge-21 — APPROVED** [review]
looks good to me!

**Review by ShaksterNano — APPROVED** [review]

**Pull request merged**
