### PR TITLE
feat: create Docker file for API

### PR DESCRIPTION
**Pull request by insertish**

### CODE REVIEW

**Comment by insertish** [comment]
you should definitely merge this

**Comment by williambl** [comment]
What needs fixing

**Comment by williambl** [comment]
Is it just the secrets in the yml file?

**Comment by insertish** [comment]
it seems by default it loads from env (cant test due to other issue) but dotenv is not invoked to load env variables from a file for example

with Docker this doesn't matter anyways because it's all loaded through env variables directly

**Comment by insertish** [comment]
MERGE READY

**Pull request merged**
